services:
  - type: web
    name: community-backend
    runtime: python
    buildCommand: bash ./build.sh
    startCommand: gunicorn --chdir community community.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: DATABASE_URL
        value: ""
    rootDir: ./
